module.exports.authController = require('./auth.controller');
module.exports.userController = require('./user.controller');
module.exports.agentController =require('./agent.controller')
module.exports.employeeController=require('./employee.controller')
module.exports.citiesController =require('./cities.controller')
module.exports.StaticContentController =require('./staticContent.controller')
module.exports.BookMarksController =require('./bookmark.controller')
module.exports.SponserController =require('./sponsorships.controller')
module.exports.ProfileController =require('./profil.controller')
